[[[0,"c:\\Users\\imeda\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\exceptiongroup\\__init__.py","","",null,0],[false,[["__all__",true,13,null],["catch",true,2,["catch",[0,"c:\\Users\\imeda\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\exceptiongroup\\_catch.py","","",null,0],12]],["format_exception",true,2,["format_exception",[0,"c:\\Users\\imeda\\.vscode\\extensions\\ms-python.vscode-pylance-2024.7.1\\dist\\typeshed-fallback\\stdlib\\traceback.pyi","","",null,0],12]],["format_exception_only",true,2,["format_exception_only",[0,"c:\\Users\\imeda\\.vscode\\extensions\\ms-python.vscode-pylance-2024.7.1\\dist\\typeshed-fallback\\stdlib\\traceback.pyi","","",null,0],12]],["print_exc",true,2,["print_exc",[0,"c:\\Users\\imeda\\.vscode\\extensions\\ms-python.vscode-pylance-2024.7.1\\dist\\typeshed-fallback\\stdlib\\traceback.pyi","","",null,0],12]],["print_exception",true,2,["print_exception",[0,"c:\\Users\\imeda\\.vscode\\extensions\\ms-python.vscode-pylance-2024.7.1\\dist\\typeshed-fallback\\stdlib\\traceback.pyi","","",null,0],12]],["BaseExceptionGroup",true,13,null],["ExceptionGroup",true,13,null],["suppress",true,2,["suppress",[0,"c:\\Users\\imeda\\.vscode\\extensions\\ms-python.vscode-pylance-2024.7.1\\dist\\typeshed-fallback\\stdlib\\contextlib.pyi","","",null,0],5]]]]]]